-- 코드를 작성해주세요
SELECT ID,IFNULL(CHILD_COUNT,0) AS CHILD_COUNT
FROM (
    SELECT PARENT_ID,COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID) E
RIGHT JOIN ECOLI_DATA AS D
ON E.PARENT_ID = D.ID
ORDER BY ID

