-- 코드를 입력하세요
SELECT U.USER_ID,U.NICKNAME,CONCAT(CITY," ",STREET_ADDRESS1," ",STREET_ADDRESS2) AS 전체주소,
    CONCAT(LEFT(U.TLNO,3),"-",SUBSTRING(U.TLNO, 4, 4),"-",RIGHT(U.TLNO,4)) AS 전화번호
FROM(
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD 
    GROUP BY WRITER_ID
    HAVING COUNT(*) >=3
)B LEFT JOIN USED_GOODS_USER U
ON B.WRITER_ID = U.USER_ID
ORDER BY U.USER_ID DESC