-- 코드를 입력하세요
SELECT V.REST_ID,I.REST_NAME,I.FOOD_TYPE,I.FAVORITES,I.ADDRESS,ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW V LEFT JOIN REST_INFO I
ON V.REST_ID = I.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY V.REST_ID
ORDER BY 6 DESC