-- 코드를 입력하세요
SELECT YEAR(B.SALES_DATE) AS YEAR,MONTH(B.SALES_DATE) AS MONTH ,A.GENDER, COUNT(DISTINCT B.USER_ID) AS USER
FROM ONLINE_SALE AS B 
LEFT JOIN USER_INFO AS A
ON B.USER_ID = A.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(B.SALES_DATE),MONTH(B.SALES_DATE),GENDER
ORDER BY YEAR, MONTH,GENDER