-- 코드를 입력하세요
# SELECT *
# FROM (
#     SELECT I.NAME,I.DATETIME
#     FROM ANIMAL_INS AS I
#     LEFT JOIN ANIMAL_OUTS AS O
#     ON I.ANIMAL_ID = O.ANIMAL_ID
#     WHERE O.DATETIME IS NULL
#     ORDER BY I.DATETIME DESC
#     LIMIT 3) AS T
# ORDER BY T.DATETIME

SELECT I.NAME,I.DATETIME
FROM ANIMAL_INS AS I
LEFT JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.DATETIME IS NULL
ORDER BY I.DATETIME 
LIMIT 3
