-- 코드를 입력하세요
WITH RECURSIVE TIMETABLE (HOUR) AS (
    SELECT 0
    UNION
    SELECT HOUR + 1 FROM TIMETABLE WHERE HOUR < 23
)
SELECT T.HOUR ,COUNT(A.ANIMAL_ID)  AS COUNT
FROM TIMETABLE AS T
LEFT JOIN ANIMAL_OUTS AS A
ON T.HOUR = HOUR(A.DATETIME)
GROUP BY HOUR
ORDER BY HOUR