-- 코드를 작성해주세요
SELECT O.ID, O.GENOTYPE , T.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS O
LEFT JOIN (SELECT ID,GENOTYPE FROM ECOLI_DATA) AS T
ON O.PARENT_ID = T.ID
WHERE (O.GENOTYPE & T.GENOTYPE) = T.GENOTYPE
ORDER BY O.ID
