-- 코드를 작성해주세요
SELECT D.ID , D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS AS D
JOIN SKILLCODES AS S1 ON S1.NAME = 'Python'
JOIN SKILLCODES AS S2 ON S2.NAME = 'C#'
WHERE (D.SKILL_CODE & S1.CODE) > 0 OR (D.SKILL_CODE & S2.CODE) > 0 
ORDER BY D.ID

