-- 코드를 작성해주세요
SELECT I.ID, N.FISH_NAME,I.LENGTH
FROM FISH_INFO AS I 
LEFT JOIN FISH_NAME_INFO AS N
ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.LENGTH = (
    SELECT MAX(F.LENGTH)
    FROM FISH_INFO AS F
    WHERE F.FISH_TYPE = I.FISH_TYPE
)
ORDER BY ID