-- 코드를 작성해주세요


SELECT D.DEPT_ID,D.DEPT_NAME_EN,E.AVG_SAL
FROM (
    SELECT DEPT_ID,ROUND(AVG(SAL),0) AS AVG_SAL 
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
) E JOIN HR_DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID
ORDER BY AVG_SAL DESC
