-- 코드를 작성해주세요
SELECT COUNT(*) AS FISH_COUNT,MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM (
    SELECT FISH_TYPE,IF(LENGTH <= 10, 10, LENGTH) AS LENGTH 
    FROM FISH_INFO
)AS T
GROUP BY T.FISH_TYPE
HAVING AVG(T.LENGTH) >= 33
ORDER BY T.FISH_TYPE


